apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-nginx-conf
data:
  nginx.conf: |
    upstream Backend {
      server spring:8080;
    }
    server {
      listen 80;
      location ~* \.(css|js|gif|jpe?g|png)$ {
        root /usr/share/nginx/html;
        index *.js;
        expires 168h;
      }
      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html =404;
      }
      location /register {
        proxy_pass http://Backend/register;
      }
      include /etc/nginx/extra-conf.d/*.conf;
    }
