apiVersion: v1
kind: Service
metadata:
  name: spring
spec:
  selector:
    app: spring
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
spec:
  selector:
    matchLabels:
      app: spring
      tier: backend
      track: stable
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spring
        tier: backend
        track: stable
    spec:
      containers:
        - image: xaq03061/myapp-spring-boot-docker
          name: spring
          ports:
            - name: spring
              containerPort: 8080
